apiVersion: v1
kind: ConfigMap
metadata:
  name: mustgather-clean-configmap
  namespace: openshift-must-gather-operator
data:
  config.yaml: |
    config:
      obfuscate:
        - type: IP
          replacementType: Consistent
          target: All
        - type: MAC
          replacementType: Consistent
          target: All
        - type: Domain
          replacementType: Consistent
          target: All
          domainNames:
            - "rhcloud.com"
            - "dev.rhcloud.com"
      omit:
        - type: Kubernetes
          kubernetesResource:
            kind: "Secret"
        - type: Kubernetes
          kubernetesResource:
            kind: "ConfigMap"
        - type: Kubernetes
          kubernetesResource:
            kind: CertificateSigningRequest
            apiVersion: certificates.k8s.io/v1
        - type: Kubernetes
          kubernetesResource:
            kind: CertificateSigningRequestList
            apiVersion: certificates.k8s.io/v1
        - type: Kubernetes
          kubernetesResource:
            kind: MachineConfig
            apiVersion: machineconfiguration.openshift.io/v1
